/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['[_nghost-%COMP%]{\n  height:100%;\n  width:calc(100% - 70px);\n  display:inline-block;\n  float:right;\n  @media (max-width: 1366px) {\n    width:calc(100% - 50px);\n  }\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3p6ZC93ZWJTdG9ybS9lZG1zL3RydW5rL2VkbXMvc3JjL2FwcC9ob21lL3Byb2plY3RGaWxlL3Byb2plY3RGaWxlLmNvbXBvbmVudC5zY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL3p6ZC93ZWJTdG9ybS9lZG1zL3RydW5rL2VkbXMvc3JjL2FwcC9ob21lL3Byb2plY3RGaWxlL3Byb2plY3RGaWxlLmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
