/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3p6ZC93ZWJTdG9ybS9lZG1zL3RydW5rL2VkbXMvc3JjL2FwcC9jb3JlL2NvbXBvbmVudC9ncmlkTGlzdC9ncmlkTGlzdC5jb21wb25lbnQuc2Nzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy96emQvd2ViU3Rvcm0vZWRtcy90cnVuay9lZG1zL3NyYy9hcHAvY29yZS9jb21wb25lbnQvZ3JpZExpc3QvZ3JpZExpc3QuY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
