/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3p6ZC93ZWJTdG9ybS9lZG1zL3RydW5rL2VkbXMvc3JjL2FwcC9ob21lL3VzZXJNYW5hZ2UvZ3JvdXAvZGlhbG9nL2Nzcy9yZW1vdmVHcm91cC5kaWFsb2cuc2Nzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy96emQvd2ViU3Rvcm0vZWRtcy90cnVuay9lZG1zL3NyYy9hcHAvaG9tZS91c2VyTWFuYWdlL2dyb3VwL2dyb3VwLmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
